contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nf-pindel channel"
    url: https://nfcore.slack.com/channels/nf-pindel
    about: Discussion about the shahcompbio/nf-pindel pipeline
